#!/bin/bash

# Copyright (C) 2009 Mathias Dahl

# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

STARTEDFILE=~/.anything-launcher-started
IDFILE=~/.anything-launcher-id

if [ -f $IDFILE ] && xdotool windowmap $(cat $IDFILE); then
    emacsclient -e "(anything-launcher)" -s anything-launcher
    xdotool windowunmap $(cat $IDFILE)
else
    rm -f $STARTEDFILE
    rm -f $IDFILE
    emacs -Q -l ~/doc/src/el/anything-load-launcher.el &
    until [ -f $STARTEDFILE ]; do
        sleep 0.1
    done
    emacsclient -e "(anything-launcher)" -s anything-launcher
    echo title search...
    sleep 1
    xdotool search -title ANYTHING-LAUNCHER | head -1 > $IDFILE
    echo id = $(cat $IDFILE), unmapping...
    xdotool windowunmap $(cat $IDFILE)
fi
